const schemaStatements = [
  `PRAGMA journal_mode = WAL;`,
  `CREATE TABLE IF NOT EXISTS users_local (
    id TEXT PRIMARY KEY NOT NULL,
    display_name TEXT,
    timezone TEXT NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    id TEXT PRIMARY KEY NOT NULL,
    tax_savings_amount REAL NOT NULL,
    estimated_tax_liability REAL NOT NULL,
    psv_due_date TEXT,
    insurance_due_date TEXT,
    max_start_shift_travel_radius_miles REAL NOT NULL,
    operator_licence_due_date TEXT,
    training_hours_completed REAL NOT NULL DEFAULT 0,
    tax_correct_to_date TEXT,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS session_state (
    id TEXT PRIMARY KEY NOT NULL,
    mode TEXT NOT NULL,
    current_area_label TEXT,
    tracking_started_at TEXT,
    tracking_stopped_at TEXT,
    business_mileage_tracking_enabled INTEGER NOT NULL,
    accumulated_online_seconds REAL NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS online_session_history (
    id TEXT PRIMARY KEY NOT NULL,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    duration_seconds INTEGER NOT NULL,
    start_area_label TEXT,
    end_area_label TEXT,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS mileage_sessions (
    id TEXT PRIMARY KEY NOT NULL,
    started_at TEXT NOT NULL,
    stopped_at TEXT,
    started_area_label TEXT,
    stopped_area_label TEXT,
    total_miles REAL NOT NULL,
    is_active INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS task_states (
    id TEXT PRIMARY KEY NOT NULL,
    completed_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS provider_imports (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    source_file_name TEXT NOT NULL,
    file_name TEXT NOT NULL,
    file_hash TEXT,
    file_signature TEXT,
    file_type TEXT NOT NULL,
    imported_at TEXT NOT NULL,
    data_start_at TEXT,
    data_end_at TEXT,
    record_count INTEGER NOT NULL,
    parse_status TEXT NOT NULL,
    parse_notes TEXT
  );`,
  `CREATE TABLE IF NOT EXISTS trips_raw (
    id TEXT PRIMARY KEY NOT NULL,
    import_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    raw_trip_id TEXT NOT NULL,
    provider_trip_id TEXT,
    row_index INTEGER NOT NULL,
    started_at TEXT,
    ended_at TEXT,
    pickup_lat REAL,
    pickup_lng REAL,
    dropoff_lat REAL,
    dropoff_lng REAL,
    pickup_area TEXT,
    dropoff_area TEXT,
    fare_gross REAL,
    surge_amount REAL,
    toll_amount REAL,
    wait_time_amount REAL,
    tip_amount REAL,
    duration_minutes REAL,
    trip_distance_miles REAL,
    status TEXT,
    raw_payload_json TEXT NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS trips_normalized (
    id TEXT PRIMARY KEY NOT NULL,
    trip_id TEXT NOT NULL,
    import_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_trip_id TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT NOT NULL,
    day_of_week TEXT NOT NULL,
    hour_bucket TEXT NOT NULL,
    week_type TEXT NOT NULL,
    pickup_area_code TEXT NOT NULL,
    dropoff_area_code TEXT NOT NULL,
    pickup_zone_key TEXT NOT NULL,
    dropoff_zone_key TEXT NOT NULL,
    pickup_lat REAL,
    pickup_lng REAL,
    dropoff_lat REAL,
    dropoff_lng REAL,
    trip_distance_miles REAL NOT NULL,
    duration_minutes REAL NOT NULL,
    fare_gross REAL NOT NULL,
    surge_amount REAL NOT NULL,
    toll_amount REAL NOT NULL,
    wait_time_amount REAL NOT NULL,
    tip_amount REAL NOT NULL,
    earnings_total REAL NOT NULL,
    inferred_dead_miles_after_trip REAL NOT NULL,
    inferred_return_to_core_miles REAL NOT NULL,
    geofence_tags_json TEXT NOT NULL,
    event_context_json TEXT NOT NULL,
    status TEXT NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS trip_truth_metrics (
    id TEXT PRIMARY KEY NOT NULL,
    trip_id TEXT NOT NULL,
    import_id TEXT NOT NULL,
    earnings_total REAL NOT NULL,
    trip_distance_miles REAL NOT NULL,
    fuel_cost REAL NOT NULL,
    maintenance_cost REAL NOT NULL,
    true_net REAL NOT NULL,
    true_net_per_hour REAL NOT NULL,
    true_net_per_mile REAL NOT NULL,
    target_gap_hourly REAL NOT NULL,
    target_gap_mile REAL NOT NULL,
    calculated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS expenses (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    category TEXT NOT NULL,
    payment_method TEXT NOT NULL DEFAULT "other",
    amount REAL NOT NULL,
    occurred_on TEXT NOT NULL,
    notes TEXT,
    receipt_required_status TEXT NOT NULL DEFAULT "none",
    receipt_source_type TEXT,
    local_receipt_uri TEXT,
    mime_type TEXT,
    original_file_name TEXT,
    file_size_bytes INTEGER,
    fuel_litres REAL,
    fuel_price_per_litre REAL,
    fuel_total REAL,
    local_sync_status TEXT NOT NULL DEFAULT "saved-local",
    cloud_synced_at TEXT,
    sync_state TEXT NOT NULL DEFAULT "local-only",
    receipt_file_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS receipt_files (
    id TEXT PRIMARY KEY NOT NULL,
    expense_id TEXT,
    local_uri TEXT NOT NULL,
    mime_type TEXT,
    original_file_name TEXT,
    file_size_bytes INTEGER,
    storage_provider TEXT NOT NULL DEFAULT "local-only",
    cloud_object_key TEXT,
    cloud_bucket TEXT,
    cloud_region TEXT,
    upload_status TEXT NOT NULL DEFAULT "local-only",
    uploaded_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS sync_jobs (
    id TEXT PRIMARY KEY NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    sync_status TEXT NOT NULL,
    last_error TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS privacy_import_files (
    id TEXT PRIMARY KEY NOT NULL,
    provider TEXT NOT NULL,
    source_file_name TEXT NOT NULL,
    local_uri TEXT,
    file_size_bytes INTEGER,
    cloud_object_key TEXT,
    cloud_bucket TEXT,
    cloud_region TEXT,
    upload_status TEXT NOT NULL DEFAULT "local-only",
    imported_at TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS vehicle_cost_history (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    mpg REAL NOT NULL,
    fuel_price_per_litre REAL NOT NULL,
    maintenance_per_mile REAL NOT NULL,
    other_cost_per_mile REAL NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS decision_targets (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    effective_from TEXT NOT NULL,
    target_hourly REAL NOT NULL,
    target_per_mile REAL NOT NULL,
    min_sample_size INTEGER NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS start_areas (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    area_code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    center_lat REAL NOT NULL,
    center_lng REAL NOT NULL,
    radius_miles REAL NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS geofences (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    area_code TEXT NOT NULL,
    name TEXT NOT NULL,
    polygon_json TEXT NOT NULL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS diary_events_cached (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    source TEXT NOT NULL,
    title TEXT NOT NULL,
    starts_at TEXT NOT NULL,
    ends_at TEXT NOT NULL,
    area_code TEXT,
    confidence_hint REAL,
    created_at TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS recommendation_snapshots (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    generated_at TEXT NOT NULL,
    action TEXT NOT NULL,
    confidence TEXT NOT NULL,
    sample_size INTEGER NOT NULL,
    basis_window_days INTEGER NOT NULL,
    rationale TEXT NOT NULL,
    payload_json TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS earnings_leaks (
    id TEXT PRIMARY KEY NOT NULL,
    user_id TEXT NOT NULL,
    trip_id TEXT NOT NULL,
    leak_type TEXT NOT NULL,
    estimated_value REAL NOT NULL,
    confidence TEXT NOT NULL,
    explanation TEXT NOT NULL,
    claim_helper_text TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
  );`,
];

export function getLocalSchemaSql(): string {
  return schemaStatements.join("\n\n");
}

export function getLocalSchemaStatements(): string[] {
  return [...schemaStatements];
}
